[project]
name = "watermark-stealing-replication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.0",
    "ipykernel>=6.30.1",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
